"""visits table

Revision ID: ce6aaa012160
Revises: 3ff47ead6589
Create Date: 2019-09-28 10:01:10.411009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6aaa012160'
down_revision = '3ff47ead6589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('visits',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('timestamp', sa.DateTime(), nullable=True),
    # sa.Column('page_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['page_id'], ['webpages.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_visits_timestamp'), 'visits', ['timestamp'], unique=False)
    # op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    with op.batch_alter_table('topics') as batch_op:
        batch_op.drop_column('last_visited')
    # op.create_index(op.f('ix_webpages_url'), 'webpages', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webpages_url'), table_name='webpages')
    op.add_column('topics', sa.Column('last_visited', sa.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_visits_timestamp'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
